# One-click release APK build (signed + minified)
# Requires android/app/keystore.properties (release signing) - generated by the release-prep step.
# JDK 17 + Android SDK in C:\Users\Administrator\android-tools
$ErrorActionPreference = 'Stop'
$tools = 'C:\Users\Administrator\android-tools'
$env:JAVA_HOME = "$tools\jdk-17.0.20+8"
$env:ANDROID_HOME = "$tools\sdk"
$env:ANDROID_SDK_ROOT = "$tools\sdk"

# Sync latest www into Android assets (otherwise the APK packages stale web assets)
$capCli = Join-Path $PSScriptRoot 'node_modules\@capacitor\cli\bin\capacitor'
if (Test-Path $capCli) {
  Write-Host '==> cap sync android'
  Set-Location $PSScriptRoot
  & node $capCli telemetry off 2>&1 | Out-Null
  & node $capCli sync android
  if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
} else {
  Write-Warning "cap CLI not found - SKIPPING sync! APK will use stale web assets."
}

# Release signing required: app/keystore.properties + release.keystore must exist
$ks = Join-Path $PSScriptRoot 'android\app\keystore.properties'
if (-not (Test-Path $ks)) {
  Write-Error "Missing $ks - release build cannot be signed. See release-prep notes."
  exit 1
}

Set-Location (Join-Path $PSScriptRoot 'android')
# 2>&1: 合并 stderr（javac 警告等）到 stdout，避免 PowerShell 将外部程序 stderr 视为终止错误
& .\gradlew.bat assembleRelease 2>&1
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

$apk = Join-Path $PSScriptRoot 'android\app\build\outputs\apk\release\app-release.apk'
if (Test-Path $apk) {
  Write-Host "BUILD OK: $apk"
} else {
  Write-Host 'Build finished but release APK not found'
}
